remote: true

experienceLevel:
 internship: true
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: true
 internship: true
 other: true
 volunteer: true

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Data Scientist
  - Data Engineer
  - Machine Learning Engineer
  - Software Engineer
  - AI Engineer
  - AI Researcher
  - Data Analyst
  - Data Science Intern
  - Data Engineer Intern
  - Machine Learning Intern
  - Data Insights Analyst

locations:
  - United States

distance: 100

companyBlacklist:
  - ""

titleBlacklist:
  - ""